### ISSUE TITLE
Request to Join GDG

### ISSUE THREAD

**Issue by elroykanye** [gdg-bambili/join-requests#3]
## Prerequisites

* [x ] Have you joined the [GDG Bambili meetup group](https://www.meetup.com/GDG-Bambili/)?

### *What* is your Meetup profile url?

* [x ] Are you part of the WhatsApp group?

### If not, *What* is your phone number?
+237 672270627

### What's your *GitHub* handle?
@elroykanye 

### What project are you interested in helping with?

gdg bambili website, developer student clubs

## Reviewers
{ cc @gdg-bambili/admins }

**Comment by ch3ck** [comment]
@elroykanye invite sent, accept it by visiting this [gdg-bambili](https://github.com/GDG-Bambili)
