### ISSUE TITLE
Request to join the GDG Bambili Community on github

### ISSUE THREAD

**Issue by yokwejuste** [gdg-bambili/join-requests#6]
## Prerequisites

* [ ] Have you joined the [GDG Bambili meetup group](https://www.meetup.com/GDG-Bambili/)?

NOT YET

### *What* is your Meetup profile url?
[This is my profile ](https://www.meetup.com/GDG-Bambili/members/yokwejuste/profile)

* [ ] Are you part of the WhatsApp group?
YES

### If not, *What* is your phone number?
+237 677 123 206 

### What's your *GitHub* handle?
@yokwejuste 

### What project are you interested in helping with?
the website and GDSC

## Reviewers
{ cc @gdg-bambili/admins }
@ch3ck

**Comment by ch3ck** [comment]
@yokwejuste invite sent. accept by visiting this link: https://github.com/gdg-bambili
